<a href="https://colab.research.google.com/github/Maneesha-17/python2025/blob/class10/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy

Q) Difference between Python List and Numpy array?

Ans) numpy array is a list which contains elements of same data type only

In [3]:
mylist = [1, 2, 3, 'abc', None]

In [2]:
import numpy as np

In [5]:
np

<module 'numpy' from '/usr/local/lib/python3.11/dist-packages/numpy/__init__.py'>

In [7]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [8]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [57]:
empty_array = np.array([])
empty_array

array([], dtype=float64)

In [58]:
int_arr = np.array([1, 2, 3])
int_arr

array([1, 2, 3])

In [59]:
int_arr = np.array([1, 2, 3], int)
int_arr

array([1, 2, 3])

In [60]:
int_arr = np.array([1, 2, 3], 'int32')
int_arr

array([1, 2, 3], dtype=int32)

In [61]:
str_arr = np.array(['ram', 'syam', 'ganesh', 'mahesh'])
str_arr

array(['ram', 'syam', 'ganesh', 'mahesh'], dtype='<U6')

In [62]:
str_arr = np.array(['ram', 'syam', 'ganesh', 'mahesh'], str)
str_arr

array(['ram', 'syam', 'ganesh', 'mahesh'], dtype='<U6')

In [63]:
str_arr = np.array(['ram', 'syam', 'ganesh', 'mahesh'], 'ascii')
str_arr

TypeError: data type 'ascii' not understood

In [97]:
comp_arr = np.array([1, 2, 3], dtype = np.complex64)
comp_arr

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)

## List vs Array

In [9]:
np.array([1, 3.3, '234', None, True])

array([1, 3.3, '234', None, True], dtype=object)

In [10]:
arr1 = np.array([1, 3.3, '234', None, True])
arr1

array([1, 3.3, '234', None, True], dtype=object)

In [12]:
type(arr1)

numpy.ndarray

In [13]:
arr1.dtype

dtype('O')

In [14]:
arr2 = np.array([12340, 12341, 12342, 12343])
arr2

array([12340, 12341, 12342, 12343])

In [15]:
type(arr2)

numpy.ndarray

In [16]:
arr2.dtype

dtype('int64')

In [17]:
arr3 = np.array([12340, 12341, 12342, 12343], float)
arr3

array([12340., 12341., 12342., 12343.])

In [18]:
arr3.dtype

dtype('float64')

In [19]:
print(f"{len(arr1) = }")
print(f"{len(arr2) = }")
print(f"{len(arr3) = }")

len(arr1) = 5
len(arr2) = 4
len(arr3) = 4


In [20]:
print(f"{arr1.shape = }")
print(f"{arr2.shape = }")
print(f"{arr3.shape = }")

arr1.shape = (5,)
arr2.shape = (4,)
arr3.shape = (4,)


In [21]:
# multi dimensional

In [23]:
arr4 = np.array([(1, 2, 3), (5, 6, 7)], float)
arr4

array([[1., 2., 3.],
       [5., 6., 7.]])

In [24]:
len(arr4)

2

In [25]:
arr4.shape

(2, 3)

In [27]:
arr5 = np.array(([1, 2, 3], (5, 6, 7)), float)
arr5

array([[1., 2., 3.],
       [5., 6., 7.]])

In [29]:
arr6 = np.array([[1, 2, 3], (5, 6, 7)], float)
arr6

array([[1., 2., 3.],
       [5., 6., 7.]])

In [31]:
arr7 = np.array([{1, 2, 3}, {5, 6, 7}], float)
arr7

TypeError: float() argument must be a string or a real number, not 'set'

### np.arange

In [33]:
arr8 = np.arange(3) # default start = 0, step = 1
arr8

array([0, 1, 2])

In [37]:
print(f"{arr8 = }")
print(f"{arr8.dtype = }")
print(f"{type(arr8) = }")
print(f"{arr8.shape = }")
print(f"{len(arr8) = }")
print(f"{arr8.ndim = }") # the number of (axes)dimensions of the array

arr8 = array([0, 1, 2])
arr8.dtype = dtype('int64')
type(arr8) = <class 'numpy.ndarray'>
arr8.shape = (3,)
len(arr8) = 3
arr8.ndim = 1


In [34]:
arr8 = np.arange(3, 15, 2) # default start = 0, step = 1
print(f"{arr8 = }")
print(f"{arr8.dtype = }")
print(f"{type(arr8) = }")
print(f"{arr8.shape = }")
print(f"{len(arr8) = }")
print(f"{arr8.ndim = }") # the number of (axes)dimensions of the array

arr8 = array([ 3,  5,  7,  9, 11, 13])
arr8.dtype = dtype('int64')
type(arr8) = <class 'numpy.ndarray'>
arr8.shape = (6,)
len(arr8) = 6
arr8.ndim = 1


In [55]:
np.linspace(3, 15, 3) # 3 is no of elements we want and it gives in equal difference

array([ 3.,  9., 15.])

In [61]:
np.linspace(3, 15, 12) # step is calaculates dynamiccaly,
                       # based on the no of values expected, from start, till end

array([ 3.        ,  4.09090909,  5.18181818,  6.27272727,  7.36363636,
        8.45454545,  9.54545455, 10.63636364, 11.72727273, 12.81818182,
       13.90909091, 15.        ])

In [62]:
np.linspace(3, 15, 234567)

array([ 3.        ,  3.00005116,  3.00010232, ..., 14.99989768,
       14.99994884, 15.        ])

If we need to disable this displaying behaviour,

use np.set_printoptions(threshold = np.nan)

#### np.reshape

In [46]:
arr8.reshape(3, 5)  #3 * 5 = 15

ValueError: cannot reshape array of size 6 into shape (3,5)

In [52]:
arr8.reshape(1, 5)

ValueError: cannot reshape array of size 6 into shape (1,5)

In [47]:
arr8.reshape(3, 2)  #3 * 2 = 6

array([[ 3,  5],
       [ 7,  9],
       [11, 13]])

In [48]:
arr8.reshape(2, 3)  # 3 * 2 = 6

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [49]:
arr8

array([ 3,  5,  7,  9, 11, 13])

In [51]:
arr8 = arr8.reshape(2, 3)  # 3 * 2 = 6
arr8

array([[ 3,  5,  7],
       [ 9, 11, 13]])

### ndarray.itemsize

  the size in bytes of each element of the array.

  For example, an array of elements of type float64 has  8 (=6itemsize4/8),
  while one of type complex32 has itemsize 4 (=32/8).

  It is equivalent to ndarray.dtype.itemsize.

In [53]:
arr8.itemsize

8

In [55]:
print(f"{arr1 = } {arr1.itemsize = }")
print(f"{arr2 = } {arr2.itemsize = }")
print(f"{arr3 = } {arr3.itemsize = }")
print(f"{arr4 = } {arr4.itemsize = }")
print(f"{arr5 = } {arr5.itemsize = }")
print(f"{arr6 = } {arr6.itemsize = }")

arr1 = array([1, 3.3, '234', None, True], dtype=object) arr1.itemsize = 8
arr2 = array([12340, 12341, 12342, 12343]) arr2.itemsize = 8
arr3 = array([12340., 12341., 12342., 12343.]) arr3.itemsize = 8
arr4 = array([[1., 2., 3.],
       [5., 6., 7.]]) arr4.itemsize = 8
arr5 = array([[1., 2., 3.],
       [5., 6., 7.]]) arr5.itemsize = 8
arr6 = array([[1., 2., 3.],
       [5., 6., 7.]]) arr6.itemsize = 8


### zeroes like and ones like

In [64]:
arr8

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [65]:
np.zeros_like(arr8)

array([[0, 0, 0],
       [0, 0, 0]])

In [66]:
np.ones_like(arr8)

array([[1, 1, 1],
       [1, 1, 1]])

In [67]:
np.zeroes(arr8)

AttributeError: module 'numpy' has no attribute 'zeroes'

In [6]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.ones([3, 4, 2], dtype = np.int16)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]], dtype=int16)

In [10]:
np.ones([3, 4, 2], dtype = np.float128)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float128)

In [11]:
np.ones([3, 4, 2], dtype = np.int16) * 356

array([[[356, 356],
        [356, 356],
        [356, 356],
        [356, 356]],

       [[356, 356],
        [356, 356],
        [356, 356],
        [356, 356]],

       [[356, 356],
        [356, 356],
        [356, 356],
        [356, 356]]], dtype=int16)

In [13]:
np.full([3, 4, 2], 356, dtype = np.int16)

array([[[356, 356],
        [356, 356],
        [356, 356],
        [356, 356]],

       [[356, 356],
        [356, 356],
        [356, 356],
        [356, 356]],

       [[356, 356],
        [356, 356],
        [356, 356],
        [356, 356]]], dtype=int16)

In [15]:
np.full([3, 3], 0.5)

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

The eye function returns matrices with ones along the kth diagonal:

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.eye(5, k = 0) # default for identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.eye(5, k = 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.eye(5, k = -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [26]:
np.eye(5, k = -56)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.identity(4, dtype = float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.identity?

In [29]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [40]:
np.identity(6, dtype = int, like = arr8)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [36]:
arr8

array([ 3,  5,  7,  9, 11, 13])

In [38]:
print(np.identity.__doc__)


    Return the identity array.

    The identity array is a square array with ones on
    the main diagonal.

    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.

    Examples
    --------
    >>> np.identity(3)
    array([[1.,  0.,  0.],
           [0.,  1.,  0.],
           [0.,  0.,  1.]])

    


In [41]:
! pip install numpy==2.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 63.7 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.61.0 requires numpy<2.2,>=1.24, but you have numpy 2.2.0 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.0 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.2.0 which is incompatible.
thinc 8.2.5 requires numpy<2.0.0,>=1.19.0; python_version >= "3.9", but you have numpy 2.2.0 which is incompatible.
langchain 0.3.18 requires numpy<2,>=1.26.4; python_version < "3.12", but you have numpy 2.2.0 which is incompatible.
pytenso

### random arrays

In [43]:
np.random.random((2, 3))

array([[0.85509274, 0.34976085, 0.2828189 ],
       [0.1832262 , 0.21439932, 0.12752415]])

In [45]:
np.empty((2, 3))

array([[0.85509274, 0.34976085, 0.2828189 ],
       [0.1832262 , 0.21439932, 0.12752415]])

In [46]:
np.array([])

array([], dtype=float64)

In [47]:
np.random.random((2, 3))

array([[0.51068752, 0.4369902 , 0.19762467],
       [0.56082482, 0.09913712, 0.99879022]])

In [48]:
np.empty((2, 3))

array([[0.51068752, 0.4369902 , 0.19762467],
       [0.56082482, 0.09913712, 0.99879022]])

In [49]:
np.empty((2, 4))# as this is not array of that dimension,

array([[2.26208247e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [50]:
np.random.random((2, 4))

array([[0.57447407, 0.82346673, 0.51706326, 0.57069571],
       [0.70345778, 0.61634476, 0.27277306, 0.54101911]])

In [51]:
np.empty((2, 4)) # empty will reuse existing arrays, if created of that dimension

array([[0.57447407, 0.82346673, 0.51706326, 0.57069571],
       [0.70345778, 0.61634476, 0.27277306, 0.54101911]])

### Arithmetic Operations

In [63]:
a = np.array([20, 30, 40])
b = np.arange(4)

In [64]:
print(a, b)

[20 30 40] [0 1 2 3]


In [65]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [124]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a, b)

[20 30 40 50] [0 1 2 3]


In [67]:
a + b # np.sum(a, b)

array([20, 31, 42, 53])

In [68]:
a - b

array([20, 29, 38, 47])

In [69]:
a * b

array([  0,  30,  80, 150])

In [70]:
a / b

<ipython-input-70-d8e10abd5ab6>:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([        inf, 30.        , 20.        , 16.66666667])

In [71]:
b / a

array([0.        , 0.03333333, 0.05      , 0.06      ])

In [72]:
a // b

<ipython-input-72-d081371454f6>:1: RuntimeWarning: divide by zero encountered in floor_divide
  a // b


array([ 0, 30, 20, 16])

In [73]:
b // a

array([0, 0, 0, 0])

In [74]:
b % a

array([0, 1, 2, 3])

In [75]:
b ** a

array([                  0,                   1,       1099511627776,
       6048575297968530377])

In [76]:
# check the case shapes are not equal

In [77]:
print(f"{a.shape = }")
print(f"{b.shape = }")

a.shape = (4,)
b.shape = (4,)


In [78]:
c = np.arange(3)

In [79]:
c.shape

(3,)

In [80]:
a + c

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [81]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [82]:
a

array([20, 30, 40, 50])

In [83]:
a < 35

array([ True,  True, False, False])

In [86]:
# assignment :compound operations,, +=, -=, *=, /=, **=

In [93]:
a += b
a

array([22, 33, 44, 55])

In [89]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [90]:
A * B

array([[2, 0],
       [0, 4]])

In [91]:
A @ B # matrix product - works only in python >= 3.5

array([[5, 4],
       [3, 4]])

In [92]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [98]:
a

array([22, 33, 44, 55])

In [99]:
a.dtype

dtype('int64')

In [100]:
a.dtype.name

'int64'

In [101]:
a * 1j

array([0.+22.j, 0.+33.j, 0.+44.j, 0.+55.j])

In [102]:
d = np.exp(a * 1j)
d

array([-0.99996083-0.00885131j, -0.01327675+0.99991186j,
        0.99984331+0.01770193j,  0.02212676-0.99975517j])

In [103]:
d.dtype

dtype('complex128')

In [138]:
a = np.array([1, 2, 3, 32, 435, 56, 68, 90, 32], float)

In [139]:
print(f"{min(a)}")
print(f"{a.min() = }")

print(f"{max(a)}")
print(f"{a.max() = }")

print(f"{sum(a)}")
print(f"{a.sum() = }")

print(f"{np.prod(a) = }")
print(f"{a.prod() = }")

print(f"{np.mean(a) = }")
print(f"{a.mean() = }")

print(f"{np.var(a) = }")
print(f"{a.var() = }")

print(f"{np.std(a) = }")
print(f"{a.std() = }")

1.0
a.min() = 1.0


In [146]:
a

array([  1.,   2.,   3.,  32., 435.,  56.,  68.,  90.,  32.])

In [147]:
a.shape

(9,)

In [148]:
a

array([  1.,   2.,   3.,  32., 435.,  56.,  68.,  90.,  32.])

In [149]:
a.reshape(3, 3)

array([[  1.,   2.,   3.],
       [ 32., 435.,  56.],
       [ 68.,  90.,  32.]])

In [150]:
a

array([  1.,   2.,   3.,  32., 435.,  56.,  68.,  90.,  32.])

In [151]:
a = a.reshape(3, 3)
a

array([[  1.,   2.,   3.],
       [ 32., 435.,  56.],
       [ 68.,  90.,  32.]])

In [154]:
print(f"{np.min(a) = }")
print(f"{a.min() = }")

print(f"{np.max(a) = }")
print(f"{a.max() = }")

print(f"{np.sum(a) = }")
print(f"{a.sum() = }")

print(f"{np.prod(a) = }")
print(f"{a.prod() = }")

print(f"{np.mean(a) = }")
print(f"{a.mean() = }")

print(f"{np.var(a) = }")
print(f"{a.var() = }")

print(f"{np.std(a) = }")
print(f"{a.std() = }")

np.min(a) = 1.0
a.min() = 1.0
np.max(a) = 435.0
a.max() = 435.0
np.sum(a) = 719.0
a.sum() = 719.0
np.prod(a) = 915967180800.0
a.prod() = 915967180800.0
np.mean(a) = 79.88888888888889
a.mean() = 79.88888888888889
np.var(a) = 16634.098765432096
a.var() = 16634.098765432096
np.std(a) = 128.97324825494664
a.std() = 128.97324825494664


In [157]:
a = np.array([2, 4, 3, 324, 56, 78, 56, 3, 889], float)
            # 0  1  2   3   4    5   6   7  8
print(f"{a.argmin() = }")
print(f"{a.argmax() = }")

a.argmin() = 0
a.argmax() = 8


In [164]:
a = np.array([[0, 2], [3, -1], [3, 5]], float)

print(a)
print(f"{a.mean() = }")
print(f"{a.mean(axis = 0)}")
print(f"{a.mean(axis = 1)}")
# print(f"{a.mean(axis = 2)}")
a.shape # shape 2 values

[[ 0.  2.]
 [ 3. -1.]
 [ 3.  5.]]
a.mean() = 2.0
[2. 2.]
[1. 1. 4.]


(3, 2)

In [166]:
a.sort() # change original
a

array([[ 0.,  2.],
       [-1.,  3.],
       [ 3.,  5.]])

In [167]:
a

array([[ 0.,  2.],
       [-1.,  3.],
       [ 3.,  5.]])

In [168]:
a = np.array([6, 2, 5, -1, 0], float)
print(f"sorted(a): {sorted(a)}")
a # won't change original

sorted(a): [-1.0, 0.0, 2.0, 5.0, 6.0]


array([ 6.,  2.,  5., -1.,  0.])

In [170]:
a = np.array([6, 2, 5, -1, 0, -1, 0, 2], float)
a.clip(0, 5)
# Values in an array can be "clipped" to be within a prespecified range.
# This is the same as applying min(max(x, minval), maxval) to each element
# x in an array.

array([5., 2., 5., 0., 0., 0., 0., 2.])

In [171]:
np.unique(a) # uniques sorted ascending

array([-1.,  0.,  2.,  5.,  6.])

In [174]:
# For two dimensional arrays, the diagonal can be extracted:

a = np.array([[1, 2], [3, 4]])
# [
#     [1, 2],
#     [3, 4]
# ]

a.diagonal()

array([1, 4])

In [175]:
np.sum(a)

10

In [176]:
np.sum(a, axis = 0) # column wise addition

array([4, 6])

In [177]:
np.sum(a, axis = 1) # row wise addition

array([3, 7])

In [179]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [180]:
# cummulative sum
b.cumsum(axis = 1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [181]:
b.cumsum(axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [182]:
b.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [183]:
b.sum()

66

In [185]:
B = np.arange(3)
B

array([0, 1, 2])

In [186]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [188]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [189]:
B ** 0.5

array([0.        , 1.        , 1.41421356])

In [190]:
B ** (1/2)

array([0.        , 1.        , 1.41421356])

In [191]:
B ** (1/3)

array([0.        , 1.        , 1.25992105])

### Array Concatenation

In [192]:
a = np.array([1, 2], float)
b = np.array([3, 4, 5, 6], float)
c = np.array([7, 8, 9], float)

np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [193]:
try:
    a + b + c
except ValueError as ex:
    print(ex)

operands could not be broadcast together with shapes (2,) (4,) 



If an array has more than one dimension, it is possible to specify the axis along which multiple arrays are concatenated. By default (without specifying the axis), NumPy concatenates along the first dimension:

In [194]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7, 8]], float)

In [195]:
try:
    np.concatenate(a, b)
except TypeError as ex:
    print(ex)

only integer scalar arrays can be converted to a scalar index


In [196]:
np.concatenate((a, b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [197]:
np.concatenate((a, b), axis = 1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

### Indexing, slicing, iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [199]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [200]:
a[2]

8

In [201]:
a[2:5]

array([ 8, 27, 64])

In [202]:
a[:6:2]

array([ 0,  8, 64])

In [203]:
# array is mutable object

In [204]:
a[:6:2] = -1000

In [205]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [206]:
a[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [207]:
for i in a:
  print(i, i ** (1/3.0))

-1000 nan
1 1.0
-1000 nan
27 3.0
-1000 nan
125 4.999999999999999
216 5.999999999999999
343 6.999999999999999
512 7.999999999999999
729 8.999999999999998


<ipython-input-207-01be797e8c39>:2: RuntimeWarning: invalid value encountered in power
  print(i, i ** (1/3.0))


In [210]:
m = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [211]:
n = m[:2, 1:3]
n

array([[2, 3],
       [6, 7]])

In [212]:
m[0, 1]

2

In [213]:
m[0, 0] = 77
m

array([[77,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [216]:
m[0, 1] = 77

In [217]:
m

array([[77, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])


Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [229]:
def f(x, y):
    return x * y


b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  0,  0,  0],
       [ 0,  1,  2,  3],
       [ 0,  2,  4,  6],
       [ 0,  3,  6,  9],
       [ 0,  4,  8, 12]])

In [232]:
b[2, 3]

6

In [233]:
b[:5, 1]

array([0, 1, 2, 3, 4])

In [234]:
b[-1]

array([ 0,  4,  8, 12])

In [235]:
c = np.array(
    [
        [[0, 1, 2], [10, 12, 13]],  # a 3D array (two stacked 2D arrays)
        [[100, 101, 102], [110, 112, 113]],
    ]
)

In [236]:
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [237]:
c.shape

(2, 2, 3)

In [238]:
c[1, ...] # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [239]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [241]:
for row in c:
  print(row)

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]


In [251]:
d = c.flatten()
d

array([  0,   1,   2,  10,  12,  13, 100, 101, 102, 110, 112, 113])

In [254]:
d.flat[10]

112

In [255]:
d.shape

(12,)

In [271]:
a = np.floor(10 * np.random.random((3, 4)))
a

array([[4., 3., 6., 1.],
       [1., 8., 9., 3.],
       [8., 1., 9., 2.]])

In [260]:
a.flatten()

array([7., 4., 3., 6., 3., 7., 8., 9., 4., 7., 4., 6.])

In [261]:
a.shape

(3, 4)

In [272]:
a

array([[4., 3., 6., 1.],
       [1., 8., 9., 3.],
       [8., 1., 9., 2.]])

In [273]:
a.ravel()

array([4., 3., 6., 1., 1., 8., 9., 3., 8., 1., 9., 2.])

In [274]:
np.ravel(a, order = 'F')

array([4., 1., 8., 3., 8., 1., 6., 9., 9., 1., 3., 2.])

In [278]:
np.ravel(a, order = 'C')

array([4., 3., 6., 1., 1., 8., 9., 3., 8., 1., 9., 2.])

In [264]:
a.shape

(3, 4)

In [265]:
a

array([[7., 4., 3., 6.],
       [3., 7., 8., 9.],
       [4., 7., 4., 6.]])

In [277]:
np.ravel?